### ISSUE TITLE
package for cadvisor?

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/packager#183]
@morpheyesh does megam needs a package for cadvisor? How do we use cadvisor in our images?

**Comment by indykish** [comment]
@morpheyesh @thomasalrin @rajthilakmca  We can't be dilly doling now. suggest a way forward.

Do we fix packager with a new `forked` package `megamcadvisor`  like megamdocker ?

**Comment by indykish** [comment]
@ranjithamca  Good work.
