### ISSUE TITLE
install_gems no such file or directory

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/packager#191]

**Comment by indykish** [comment]
@thomasalrin  fixed  ?

**Comment by thomasalrin** [comment]
@indykish Need to check. @vijaykanthm28 Did you face this problem, in last dc setup? Check it out.

**Comment by vijaykanthm28** [comment]
@indykish @thomasalrin  yeah this promblem fixed

**Comment by thomasalrin** [comment]
ok
