### ISSUE TITLE
Test the retrofitted basho's riak package as the leveldb setting is missing

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/packager#200]

**Comment by indykish** [comment]
@arunkumarsekar06  check out current package in a VM.

**Comment by indykish** [comment]
We download the deb from [http://docs.basho.com/riak/latest/downloads/](riak). For the convenience of customers we have updated the `/etc/riak/riak.conf` setting called `storage: bitcask` to `storage: leveldb`.

Apparently for this customer, the setting wasn't there. This setting `storage: leveldb` provides secondary index abililty for us.

This is a test activity.

**Comment by indykish** [comment]
@arunkumarsekar06  Fixed ?

**Comment by indykish** [comment]
@thomasalrin  fixed  ?

**Comment by thomasalrin** [comment]
@indykish as we discussed, we shall install prereqs like riak, nsq using megdc. There we can configure riak using sed command.

**Comment by indykish** [comment]
megdc update.
